name: Setup Node.js 22 LTS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 22 LTS
        uses: actions/setup-node@v3
        with:
          node-version: 22
          check-latest: true

      - name: Verify npm version
        run: npm -v
