on:
  push:
    branches:
    - main
    - release/*

jobs:
  setup_node_job:
    name: Setup Node.js environment
    runs-on: ubuntu-latest
    steps:
    - name: Setup Node.js environment
    - uses: actions/setup-node@v4.1.0
 
 
